2021-04-19 11:42:13,886 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-19 11:42:37,651 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-19 11:42:39,765 ERROR: Exception on /index [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 75, in index
    'body': "Mode: " + post_dict['id']
TypeError: can only concatenate str (not "int") to str
2021-04-19 11:42:59,341 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-19 11:44:13,641 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:26:44,329 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:28:16,153 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:53:35,928 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:56:13,825 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:56:55,098 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 09:56:57,569 ERROR: Exception on / [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 47, in index
    r = requxests.put(url = URL_post, data = data_post)
NameError: name 'requxests' is not defined
2021-04-21 09:57:11,122 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:05:09,203 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:07:11,620 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:07:58,946 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:09:51,711 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:10:36,288 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:11:16,882 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:18:19,374 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:18:54,940 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:19:57,842 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:20:53,525 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-21 10:25:57,207 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:42:36,854 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:42:51,434 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:51:23,692 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:52:40,656 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:52:42,482 ERROR: Exception on / [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 75, in index
    'body': r['mode']
TypeError: 'Response' object is not subscriptable
2021-04-22 21:53:03,551 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:53:04,898 ERROR: Exception on / [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 75, in index
    'body': r.txt
AttributeError: 'Response' object has no attribute 'txt'
2021-04-22 21:53:17,540 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-04-22 21:53:18,547 ERROR: Exception on / [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 75, in index
    'body': str(r.txt)
AttributeError: 'Response' object has no attribute 'txt'
2021-04-22 21:53:27,984 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
