2021-03-16 21:15:15,661 ERROR: Exception on /login [GET] [in /home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/classroomLEDs/webApp/app/routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/whzheng/classroomLEDs/webApp/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/whzheng/classroomLEDs/webApp/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/whzheng/classroomLEDs/webApp/app/templates/base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/whzheng/classroomLEDs/webApp/app/templates/login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/whzheng/classroomLEDs/webApp/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2021-03-16 21:17:03,019 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-16 21:21:44,713 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:10:46,021 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:23:13,451 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:27:07,222 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:31:44,055 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:50:09,532 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
2021-03-17 10:50:56,167 INFO: WebApp startup [in /home/whzheng/classroomLEDs/webApp/app/__init__.py:45]
